const CURATED_CP = [
{"id":"cp-138","article":"138","title":"Homicidi","keywords":["homicidi","matar","mort","assassinat"],"summary":"Qui mati una altra persona comet homicidi. Pena: presó de 10 a 15 anys. En els supòsits d’assassinat, s’apliquen les penes més greus dels articles següents."},
{"id":"cp-147","article":"147","title":"Lesions","keywords":["lesions","agressió","cops","ferides","salut","maltractament"],"summary":"Causar una lesió que afecti la integritat corporal o la salut pot constituir delicte. Si requereix tractament mèdic o quirúrgic, la pena pot ser de presó de 3 mesos a 3 anys o multa de 6 a 12 mesos. Les lesions lleus poden comportar multa."},
{"id":"cp-148","article":"148","title":"Lesions agreujades","keywords":["lesions","armes","greus","vulnerable"],"summary":"Les lesions de l’article 147 s’agreugen quan es cometen amb armes o instruments perillosos, amb crueltat o contra persones especialment vulnerables. Pena: presó de 2 a 5 anys."},
{"id":"cp-153","article":"153","title":"Violència de gènere i domèstica","keywords":["violència","gènere","domèstica","parella","maltractament"],"summary":"Castiga les lesions lleus o el maltractament físic o psíquic en els supòsits previstos per la llei, especialment en l’àmbit de la parella o familiar. Les penes poden incloure presó, treballs en benefici de la comunitat i privació del dret a tenir armes."},
{"id":"cp-169","article":"169","title":"Amenaces","keywords":["amenaces","amenaça","intimidació","mort"],"summary":"Amenaces amb un mal que constitueixi delicte. La pena varia segons la gravetat, el tipus d’amenaça i les circumstàncies. Pot comportar presó o multa."},
{"id":"cp-172","article":"172","title":"Coaccions","keywords":["coaccions","violència","obligar","impedir","llibertat"],"summary":"Impedir amb violència que una persona faci allò que la llei no prohibeix, o obligar-la a fer allò que no vol, pot constituir delicte de coaccions. Pena general: presó de 6 mesos a 3 anys o multa de 12 a 24 mesos."},
{"id":"cp-173","article":"173","title":"Tracte degradant i violència habitual","keywords":["tracte degradant","violència habitual","humiliació","domèstica"],"summary":"El tracte degradant que lesioni greument la integritat moral i la violència física o psíquica habitual en l’àmbit familiar poden constituir delicte. Les penes varien segons la conducta i les circumstàncies."},
{"id":"cp-178","article":"178","title":"Agressió sexual","keywords":["agressió sexual","consentiment","llibertat sexual","violació"],"summary":"Realitzar un acte que atempti contra la llibertat sexual d’una altra persona sense consentiment constitueix agressió sexual. La pena depèn de les circumstàncies del fet i de la seva gravetat."},
{"id":"cp-202","article":"202","title":"Allanament de morada","keywords":["allanament","domicili","entrada","casa","habitatge"],"summary":"Entrar en un domicili aliè o mantenir-s’hi contra la voluntat del morador pot constituir allanament de morada. Pena general: presó de 6 mesos a 2 anys. Amb violència o intimidació, la pena s’agreuja."},
{"id":"cp-234","article":"234","title":"Furt","keywords":["furt","hurto","robatori","sostracció","coses mobles","ànim de lucre"],"summary":"Prendre una cosa moble aliena amb ànim de lucre i sense la voluntat del propietari constitueix furt. Si el valor no supera 400 €, és delicte lleu i pot comportar multa d’1 a 3 mesos. Si supera 400 €, la pena general és de presó de 6 a 18 mesos."},
{"id":"cp-237","article":"237","title":"Robatori amb força en les coses","keywords":["robatori","força","escalada","fractura","claus falses","alarma"],"summary":"Hi ha robatori amb força quan s’utilitzen mitjans com fractura, escalada, claus falses o forçament per apoderar-se de béns aliens. Pena general: presó d’1 a 3 anys, amb agreujaments en determinats llocs o circumstàncies."},
{"id":"cp-242","article":"242","title":"Robatori amb violència o intimidació","keywords":["robatori","violència","intimidació","atracament","armes"],"summary":"Apoderar-se de béns aliens utilitzant violència o intimidació constitueix robatori amb violència o intimidació. Pena general: presó de 2 a 5 anys. La pena s’agreuja en determinats supòsits."},
{"id":"cp-244","article":"244","title":"Sostracció de vehicles a motor","keywords":["sostracció","vehicle","cotxe","moto"],"summary":"Apoderar-se d’un vehicle a motor o ciclomotor aliè sense ànim d’apropiar-se’l pot constituir aquest delicte. Les penes depenen de si hi ha força i de les circumstàncies del fet."},
{"id":"cp-248","article":"248","title":"Estafa","keywords":["estafa","engany","lucre","phishing"],"summary":"L’estafa consisteix a utilitzar engany per provocar error en una altra persona i aconseguir un acte de disposició en perjudici propi o aliè. La pena varia segons la quantia i les circumstàncies."},
{"id":"cp-263","article":"263","title":"Danys","keywords":["danys","destrosses","vandalisme","propietat"],"summary":"Causar danys en propietat aliena pot constituir delicte. La pena depèn de la quantia del dany i de les circumstàncies. En determinats casos s’apliquen penes més greus."},
{"id":"cp-368","article":"368","title":"Tràfic de drogues","keywords":["drogues","tràfic","estupefaents","cànnabis","cocaïna","heroïna"],"summary":"El cultiu, elaboració o tràfic de drogues, o facilitar-ne el consum il·legal, constitueix delicte. Les penes varien segons la substància i les circumstàncies, i poden incloure presó i multa."},
{"id":"cp-379","article":"379","title":"Conducció sota la influència d’alcohol o drogues","keywords":["alcohol","drogues","conducció","alcoholèmia","positiu"],"summary":"Conduir sota la influència d’alcohol o drogues pot constituir delicte. També s’aplica la via penal quan se superen els llindars legals d’alcoholèmia. Les penes poden incloure presó o multa i privació del dret a conduir."},
{"id":"cp-384","article":"384","title":"Conducció sense permís","keywords":["sense carnet","permís","llicència","punts"],"summary":"Conduir sense haver obtingut mai el permís, amb el permís retirat per pèrdua total de punts o després d’una condemna de privació del dret a conduir pot constituir delicte. Les penes poden incloure presó, multa o treballs en benefici de la comunitat."},
{"id":"cp-510","article":"510","title":"Discursos d’odi i discriminació","keywords":["odi","discriminació","racisme","xenofòbia","incitació"],"summary":"Fomentar o incitar públicament a l’odi, hostilitat, discriminació o violència contra grups protegits per la llei pot constituir delicte. Les penes poden incloure presó i multa."},
{"id":"cp-550","article":"550","title":"Atemptat contra l’autoritat","keywords":["atemptat","autoritat","agent","policia","resistència","agressió"],"summary":"Agredir, acometre o oferir resistència activa greu amb violència o intimidació a l’autoritat, als seus agents o funcionaris en l’exercici de les seves funcions pot constituir atemptat. La pena depèn de la víctima i de les circumstàncies."},
{"id":"cp-556","article":"556","title":"Resistència i desobediència","keywords":["resistència","desobediència","agent","policia","ordre"],"summary":"Resistir o desobeir greument l’autoritat o els seus agents en l’exercici de les seves funcions pot constituir delicte. Pena general: presó de 3 mesos a 1 any o multa de 6 a 18 mesos."},
{"id":"cp-557","article":"557","title":"Desordres públics","keywords":["desordres","tumult","altercats","via pública","violència"],"summary":"Actuar en grup per alterar greument la pau pública, causar lesions o danys, obstaculitzar vies o envair instal·lacions pot constituir delicte de desordres públics. La pena depèn de la conducta i de les circumstàncies."},
{"id":"cp-559","article":"559","title":"Missatges que incitin a desordres públics","keywords":["incitació","xarxes","missatges","desordres","tumult"],"summary":"Difondre públicament missatges o consignes que incitin a cometre desordres públics pot constituir delicte. Pena: presó de 3 mesos a 1 any o multa de 6 a 12 mesos."}
];

const state={data:{'codi-penal':CURATED_CP,lecrim:[],circulacio:[],ordenanca:[],seguretat:[]},history:[],favorites:[]};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const eq={furt:['furt','hurto'],robatori:['robatori','robo'],violencia:['violencia','violència'],lesions:['lesions','lesiones'],desobediencia:['desobediencia','desobediència'],resistencia:['resistencia','resistència'],atemptat:['atemptat','atentado'],amenaces:['amenaces','amenazas'],coaccions:['coaccions','coacciones'],drogues:['drogues','drogas'],alcohol:['alcohol']};
function terms(q){return norm(q).split(/\s+/).filter(Boolean).map(t=>eq[t]||[t]);}
function curated(article){return CURATED_CP.find(x=>String(x.article).toLowerCase()===String(article).toLowerCase());}
function current(){return document.querySelector('.tab.active')?.dataset.tab||'codi-penal';}
function loadSaved(){try{state.favorites=JSON.parse(localStorage.getItem('1312_favorits')||'[]');state.history=JSON.parse(localStorage.getItem('1312_historial')||'[]');}catch(e){}}
function penalty(item){const m=String(item?.summary||'').match(/(?:pena|penes|presó|multa)[^.!?]*(?:[.!?]|$)/i);return m?m[0].trim():'';}
function short(v,n){v=String(v||'').replace(/\s+/g,' ').trim();return v.length<=n?v:v.slice(0,n).replace(/\s+\S*$/,'')+'…';}
function card(item){const ca=curated(item.article);const title=ca?.title||'Article '+item.article;const summary=ca?.summary||'';return '<button class="result-card" data-id="'+esc(item.id)+'" type="button"><div class="result-top"><span>Art. '+esc(item.article)+'</span><strong>'+esc(title)+'</strong></div>'+(summary?'<small>RESUM</small><p>'+esc(short(summary,220))+'</p>':'<p class="pending">Fitxa resumida en català pendent de revisió.</p>')+(penalty(ca||item)?'<small class="penalty-label">PENES</small><p class="penalty">'+esc(short(penalty(ca||item),150))+'</p>':'')+'<em>Ampliar fitxa →</em></button>';}
function hero(){const p=document.getElementById('codi-penal');p.innerHTML='<section class="cp-hero"><img src="logo.png" alt="1312"><div class="hero-badge">1312</div><h2>Codi Penal</h2><p>Cerca un article, un delicte o una paraula clau.</p><div class="hero-stat"><strong>'+state.data['codi-penal'].length+'</strong><span>articles disponibles</span></div></section><div class="quick-title">Cerques ràpides</div><div class="quick-grid">'+[['Furt','furt'],['Robatori','robatori'],['Lesions','lesions'],['Violència','violència'],['Atemptat','atemptat'],['Desobediència','desobediència']].map(x=>'<button type="button" data-q="'+x[1]+'">'+x[0]+'</button>').join('')+'</div><p class="hero-note">Escriu al cercador de dalt per consultar la normativa.</p>';p.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const i=document.getElementById('search-input');i.value=b.dataset.q;search(b.dataset.q);i.focus();});}
function search(q){if(current()!=='codi-penal')return;if(!q.trim()){hero();return;}const ts=terms(q);const items=state.data['codi-penal'].filter(x=>{const ca=curated(x.article);const s=norm([x.article,x.title,x.summary,x.text,ca?.title,ca?.summary,...(x.keywords||[]),...(ca?.keywords||[])].join(' '));return ts.every(group=>group.some(t=>s.includes(t)));});renderResults(items);}
function renderResults(items){const p=document.getElementById('codi-penal');p.innerHTML='<div class="search-head"><strong>'+items.length+' resultat'+(items.length!==1?'s':'')+'</strong><button type="button" id="clearSearch">× Netejar</button></div>'+(items.length?items.map(card).join(''):'<div class="empty-search">No s’han trobat articles. Prova amb una altra paraula.</div>');document.getElementById('clearSearch')?.addEventListener('click',()=>{document.getElementById('search-input').value='';hero();});p.querySelectorAll('.result-card').forEach(b=>b.onclick=()=>openArticle(b.dataset.id));}
function openArticle(id,push=true){const raw=state.data['codi-penal'].find(x=>x.id===id);if(!raw)return;const ca=curated(raw.article)||raw;const p=document.getElementById('codi-penal');if(push)history.pushState({view:'article',id},'');p.innerHTML='<button class="detail-back" type="button">← Tornar als resultats</button><article class="cp-detail"><div class="detail-number">ARTICLE '+esc(ca.article)+'</div><h2>'+esc(ca.title||('Article '+ca.article))+'</h2><div class="detail-box"><small>RESUM</small><p>'+esc(ca.summary||'Fitxa resumida en català pendent de revisió.')+'</p>'+(penalty(ca)?'<small class="penalty-label">PENES</small><p class="penalty">'+esc(penalty(ca))+'</p>':'')+'</div><p class="detail-source">Font normativa: Codi Penal. Aquesta fitxa és una síntesi de consulta i no substitueix el text legal oficial.</p></article>';p.querySelector('.detail-back').onclick=()=>history.back();}
function switchTab(tab,push=true){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===tab));const input=document.getElementById('search-input');input.value='';if(tab==='codi-penal')hero();else document.getElementById(tab).innerHTML='<div class="placeholder-panel"><strong>'+esc(tab)+'</strong><p>Aquesta secció continuarà incorporant la base normativa completa.</p></div>';if(push)history.pushState({view:'tab',tab},'');}
async function loadOfficial(){try{const r=await fetch('./data/normativa-oficial.json',{cache:'no-store'});if(!r.ok)return;const j=await r.json();for(const [k,items] of Object.entries(j.data||{})){if(!Array.isArray(items)||!items.length)continue;if(k==='codi-penal'){const map=new Map(items.map(x=>[String(x.article),x]));for(const ca of CURATED_CP){const o=map.get(String(ca.article));if(o)Object.assign(o,ca);else items.push(ca);}state.data[k]=items;}else state.data[k]=items;}hero();}catch(e){console.warn('No s’ha pogut carregar la base oficial',e);}}
function init(){loadSaved();history.replaceState({view:'home'},'');document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchTab(t.dataset.tab));const input=document.getElementById('search-input');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),180);};input.onkeydown=e=>{if(e.key==='Enter')search(input.value);};window.onpopstate=e=>{const s=e.state||{view:'home'};if(s.view==='article'){openArticle(s.id,false);return;}switchTab(s.tab||'codi-penal',false);};hero();loadOfficial();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
document.addEventListener('DOMContentLoaded',init);
