/* Codi Penal 1312 — capa visual i fitxa ampliada */
const CP_EXTENDED={
  '138':{context:'Protegeix la vida humana independent i sanciona la conducta de causar la mort d’una altra persona.',details:'La qualificació concreta depèn de com s’hagi produït el fet. L’homicidi es diferencia de l’assassinat perquè aquest últim incorpora circumstàncies específiques d’especial gravetat.',aggravation:'L’assassinat pot comportar penes més elevades quan concorren les circumstàncies previstes pel Codi Penal.',penalty:'Presó de 10 a 15 anys per l’homicidi bàsic.'},
  '147':{context:'Protegeix la integritat corporal i la salut física o mental. No tota lesió té la mateixa resposta penal: és especialment rellevant si ha requerit tractament mèdic o quirúrgic.',details:'També es preveuen supòsits de lesions lleus. La valoració depèn del tipus de lesió, del tractament necessari i de les circumstàncies de la víctima i del fet.',aggravation:'Les lesions poden passar a tipus més greus quan concorren les circumstàncies específiques dels articles següents.',penalty:'En el supòsit bàsic amb tractament: presó de 3 mesos a 3 anys o multa de 6 a 12 mesos.'},
  '148':{context:'És una forma agreujada de les lesions quan la manera de cometre-les o les circumstàncies del fet revelen una major gravetat.',details:'Entre les circumstàncies hi ha l’ús d’armes o instruments perillosos, l’ensanyament o determinades situacions de vulnerabilitat de la víctima.',aggravation:'La pena s’aplica en els casos previstos expressament per l’article 148 i segons les circumstàncies concretes.',penalty:'Presó de 2 a 5 anys.'},
  '153':{context:'Regula determinades lesions lleus i actes de maltractament físic o psíquic dins de l’àmbit familiar o de parella.',details:'La resposta penal varia segons la relació entre autor i víctima i segons si existeixen circumstàncies especials. També pot afectar les prohibicions relacionades amb armes.',aggravation:'La pena pot variar quan els fets es produeixen en determinades circumstàncies, amb armes o davant de menors, entre altres supòsits.',penalty:'Pot incloure presó, treballs en benefici de la comunitat i privació del dret a tenir armes.'},
  '169':{context:'Protegeix la llibertat i la tranquil·litat davant l’anunci d’un mal que constitueixi delicte.',details:'La responsabilitat depèn del contingut de l’amenaça, de si es condiciona a alguna exigència i de les circumstàncies en què es realitza.',aggravation:'La pena canvia segons la gravetat del mal anunciat, la condició imposada i altres circumstàncies previstes legalment.',penalty:'Pot comportar presó o multa segons el supòsit.'},
  '172':{context:'Protegeix la llibertat d’actuar davant qui, mitjançant violència, impedeix a una persona fer allò que la llei no prohibeix o l’obliga a fer allò que no vol.',details:'La conducta pot consistir tant en impedir com en obligar. La valoració depèn de la violència utilitzada i de les circumstàncies del fet.',aggravation:'Hi ha modalitats específiques amb conseqüències diferents segons la víctima, la conducta i l’àmbit en què es produeix.',penalty:'En el tipus general: presó de 6 mesos a 3 anys o multa de 12 a 24 mesos.'},
  '173':{context:'Protegeix la integritat moral i també contempla la violència física o psíquica habitual en determinats àmbits familiars.',details:'El tracte degradant pot constituir delicte quan produeix una greu afectació de la integritat moral. En la violència habitual és important la reiteració de conductes.',aggravation:'Les penes varien segons la relació amb la víctima, l’habitualitat i altres circumstàncies.',penalty:'La pena depèn del supòsit concret.'},
  '178':{context:'Protegeix la llibertat sexual i parteix de la necessitat que qualsevol acte sexual compti amb consentiment.',details:'La qualificació depèn de l’acte realitzat, de les circumstàncies i de les condicions de la víctima. El Codi Penal diferencia diversos supòsits i graus de gravetat.',aggravation:'Les circumstàncies específiques poden elevar considerablement la resposta penal.',penalty:'La pena varia segons el tipus d’agressió i les circumstàncies.'},
  '202':{context:'Protegeix la inviolabilitat del domicili. Entrar o mantenir-se en una morada aliena contra la voluntat del morador pot constituir delicte.',details:'La conducta pot consistir en entrar sense autorització o en no abandonar el domicili quan el morador ho exigeix.',aggravation:'L’ús de violència o intimidació comporta un tractament penal més greu.',penalty:'Tipus bàsic: presó de 6 mesos a 2 anys.'},
  '234':{context:'El furt consisteix a prendre una cosa moble aliena amb ànim de lucre i sense consentiment del seu titular.',details:'La quantia del que s’ha sostret és especialment rellevant per determinar si s’aplica el tipus general o el delicte lleu.',aggravation:'La reiteració de determinades conductes i altres circumstàncies poden modificar la resposta penal.',penalty:'Si el valor supera 400 €: presó de 6 a 18 mesos. Fins a 400 €: multa d’1 a 3 mesos, en el supòsit previst.'},
  '237':{context:'Hi ha robatori quan, a més de l’ànim d’apropiació, s’utilitza força sobre les coses o violència/intimidació sobre les persones.',details:'La força pot incloure fractura, escalada, claus falses o altres mitjans previstos pel Codi Penal.',aggravation:'La pena s’incrementa en determinats llocs, circumstàncies o formes d’execució.',penalty:'Tipus general: presó d’1 a 3 anys.'},
  '242':{context:'És el robatori comès mitjançant violència o intimidació sobre les persones.',details:'La violència o intimidació ha d’estar vinculada a l’apoderament. Les circumstàncies concretes determinen la pena aplicable.',aggravation:'L’ús d’armes o instruments perillosos i altres circumstàncies poden agreujar la resposta penal.',penalty:'Tipus general: presó de 2 a 5 anys.'},
  '244':{context:'Regula la sostracció o utilització no autoritzada de vehicles a motor o ciclomotors en els supòsits previstos.',details:'És rellevant si existeix intenció d’apropiar-se del vehicle o simplement d’utilitzar-lo temporalment i retornar-lo.',aggravation:'La força utilitzada per prendre el vehicle i altres circumstàncies poden modificar la pena.',penalty:'La pena varia segons la modalitat i les circumstàncies.'},
  '248':{context:'L’estafa parteix d’un engany que provoca un error en una altra persona i la porta a realitzar un acte de disposició patrimonial perjudicial.',details:'Han de valorar-se l’engany, l’error, l’acte de disposició, el perjudici i l’ànim de lucre. Les estafes informàtiques tenen regulació específica.',aggravation:'La quantia del perjudici i determinades circumstàncies poden agreujar la pena.',penalty:'La pena varia segons la quantia i les circumstàncies.'},
  '263':{context:'Protegeix el patrimoni davant la destrucció, deteriorament o inutilització de béns d’una altra persona.',details:'La quantia del perjudici és important per determinar el tractament penal. També existeixen supòsits específics més greus.',aggravation:'Determinats béns, finalitats o circumstàncies poden portar a penes més elevades.',penalty:'La pena depèn principalment de la quantia i de les circumstàncies.'},
  '368':{context:'Sanciona el cultiu, elaboració, tràfic i altres conductes relacionades amb facilitar el consum il·legal de drogues tòxiques, estupefaents o substàncies psicotròpiques.',details:'La resposta penal diferencia, entre altres factors, la naturalesa i gravetat de la substància i la conducta realitzada.',aggravation:'Existeixen nombroses circumstàncies agreujants específiques.',penalty:'Pot comportar presó i multa; la durada depèn de la substància i del supòsit.'},
  '379':{context:'Sanciona determinades conductes de conducció sota la influència d’alcohol o drogues i els supòsits d’alcoholèmia que superen els llindars penals.',details:'La via penal no es limita al resultat d’una prova: també és rellevant la influència real de l’alcohol o les drogues sobre la conducció.',aggravation:'La situació concreta, els nivells detectats i altres conductes poden donar lloc a responsabilitats addicionals.',penalty:'Pot incloure presó, multa o treballs en benefici de la comunitat i privació del dret a conduir.'},
  '384':{context:'Protegeix la seguretat viària davant determinades situacions de conducció sense habilitació legal.',details:'Inclou conduir després d’haver perdut la vigència del permís per pèrdua total de punts, després d’una privació judicial o sense haver obtingut mai el permís.',aggravation:'La situació administrativa o judicial concreta determina el supòsit aplicable.',penalty:'Pot incloure presó, multa o treballs en benefici de la comunitat.'},
  '510':{context:'Protegeix els col·lectius especialment protegits davant conductes públiques d’odi, hostilitat, discriminació o violència.',details:'La responsabilitat depèn del contingut, la forma de difusió, la finalitat i el col·lectiu afectat.',aggravation:'El Codi Penal preveu modalitats i circumstàncies que poden elevar la pena.',penalty:'Pot incloure presó i multa segons el supòsit.'},
  '550':{context:'Protegeix l’autoritat, els seus agents i determinats funcionaris davant agressions, violència o intimidació greus durant l’exercici de les seves funcions.',details:'És important que l’actuació estigui relacionada amb l’exercici de la funció pública protegida.',aggravation:'La pena varia segons la persona protegida, la intensitat de la violència i altres circumstàncies.',penalty:'La pena depèn de la víctima i de les circumstàncies del fet.'},
  '556':{context:'Sanciona determinades conductes de resistència o desobediència greu davant l’autoritat o els seus agents.',details:'No qualsevol incompliment d’una ordre és delicte. Cal valorar el caràcter greu de la resistència o desobediència i el context de l’actuació.',aggravation:'La naturalesa de la conducta i la condició de la persona davant la qual es produeix poden influir en la resposta.',penalty:'En el supòsit general: presó de 3 mesos a 1 any o multa de 6 a 18 mesos.'},
  '557':{context:'Protegeix la pau pública davant actuacions col·lectives que alteren greument la normal convivència.',details:'El delicte contempla diferents formes d’actuació col·lectiva, inclosos actes violents, danys o alteracions greus de la normalitat.',aggravation:'Les lesions, danys, ús d’armes i altres circumstàncies poden modificar la pena.',penalty:'La pena varia segons la conducta i les circumstàncies.'},
  '559':{context:'Sanciona determinades formes públiques d’incitació a cometre desordres públics.',details:'La conducta se centra en la difusió de missatges o consignes amb capacitat d’incitar a cometre els actes previstos per la norma.',aggravation:'La responsabilitat depèn del contingut del missatge, la seva difusió i les circumstàncies.',penalty:'Presó de 3 mesos a 1 any o multa de 6 a 12 mesos.'}
};
function cpEnhanceDetail(){
  const box=document.querySelector('#codi-penal .cp-detail');
  if(!box||box.dataset.enhanced)return;
  const n=(box.querySelector('.detail-number')?.textContent.match(/\d+/)||[])[0];
  const x=CP_EXTENDED[n]; if(!x)return;
  box.dataset.enhanced='1';
  const source=box.querySelector('.detail-source');
  const wrap=document.createElement('div');wrap.className='detail-expanded';
  wrap.innerHTML='<section><span>EN QUÈ CONSISTEIX</span><p>'+x.context+'</p></section><section><span>INFORMACIÓ IMPORTANT</span><p>'+x.details+'</p></section><section><span>QUAN POT SER MÉS GREU</span><p>'+x.aggravation+'</p></section><section class="expanded-penalty"><span>PENA ORIENTATIVA</span><p>'+x.penalty+'</p></section>';
  if(source)box.insertBefore(wrap,source); else box.appendChild(wrap);
}
const cpObserver=new MutationObserver(()=>cpEnhanceDetail());
function startCPEnhance(){const target=document.getElementById('codi-penal');if(target){cpObserver.observe(target,{childList:true,subtree:true});cpEnhanceDetail();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startCPEnhance);else startCPEnhance();
